import type { Static } from "typebox";
import type * as Action from "./bridge-action-contracts.ts";
import type * as Core from "./bridge-core-contracts.ts";

type HostContext = unknown;
type HostAbortSignal = unknown;
type PersistedPermissionsEntry = unknown;
type ChildMetadataHostValue = unknown;
type HostGoalEntry = unknown;

export type CoreMethodArgs = {
  readonly toolPolicyNames: readonly [];
  readonly allowedToolNames: readonly [];
  readonly commandSpecs: readonly [];
  readonly planActiveToolsSync: readonly [Static<typeof Core.ActiveToolsSyncFactsSchema>];
  readonly planEnvironmentContext: readonly [HostContext, Static<typeof Core.EnvironmentContextFactsSchema>];
  readonly resolveSkillMentions: readonly [Static<typeof Core.SkillResolveFactsSchema>];
  readonly listSkills: readonly [Static<typeof Core.SkillListFactsSchema>];
  readonly planCompactionModelCommand: readonly [Static<typeof Core.CompactionCommandFactsSchema>];
  readonly planSessionBeforeCompact: readonly [Static<typeof Core.CompactionSettingsSchema>];
  readonly refreshExecPolicy: readonly [Static<typeof Core.RefreshExecPolicyFactsSchema>];
  readonly appendExecPolicyAllowRule: readonly [Static<typeof Core.ExecPolicyAllowRuleFactsSchema>];
  readonly sandboxMetadataDirNames: readonly [];
  readonly validateWorkspaceMutationPaths: readonly [Static<typeof Core.WorkspaceMutationFactsSchema>];
  readonly sandboxHostPathPlan: readonly [Static<typeof Core.SandboxHostPathFactsSchema>];
  readonly planChildSessionStart: readonly [Static<typeof Core.ChildSessionStartFactsSchema>, HostContext];
  readonly planChildDispatch: readonly [Static<typeof Core.ChildDispatchFactsSchema>];
  readonly planChildPermissionRefresh: readonly [PersistedPermissionsEntry, ChildMetadataHostValue, HostContext];
  readonly prepareTool: readonly [Static<typeof Action.PrepareToolFactsSchema>];
  readonly applyPatchToFiles: readonly [Static<typeof Core.PatchApplicationFactsSchema>];
  readonly applyEditToFile: readonly [Static<typeof Core.EditApplicationFactsSchema>];
  readonly planExecHostCall: readonly [Static<typeof Action.PreparedExecInputSchema>, HostContext];
  readonly formatExecResult: readonly [Static<typeof Action.PreparedExecInputSchema>, Static<typeof Core.HostExecResultSchema>, boolean, boolean];
  readonly planExecApprovalPrompt: readonly [Static<typeof Core.ExecApprovalPromptFactsSchema>];
  readonly finishExecApproval: readonly [Static<typeof Core.ExecApprovalOutcomeFactsSchema>];
  readonly discardAuthorityPlan: readonly [Static<typeof Core.AuthorityPlanRefSchema>];
  readonly reissueExecPlan: readonly [Static<typeof Core.AuthorityPlanRefSchema>];
  readonly planWriteStdinHostCall: readonly [Static<typeof Action.PreparedWriteStdinSchema>, HostContext];
  readonly runExecCommand: readonly [Static<typeof Action.PreparedExecSchema>, string, HostAbortSignal, HostContext];
  readonly writeExecStdin: readonly [Static<typeof Core.WriteStdinFactsSchema>];
  readonly readFile: readonly [Static<typeof Core.ReadFileFactsSchema>];
  readonly viewMedia: readonly [Static<typeof Core.ViewMediaFactsSchema>];
  readonly shutdownExecOwner: readonly [string];
  readonly pendingExecNotifications: readonly [string];
  readonly claimExecNotificationDelivery: readonly [string, number];
  readonly releaseExecNotificationDelivery: readonly [number];
  readonly markExecNotificationDelivered: readonly [number];
  readonly awaitExecCompletion: readonly [number];
  readonly planCommandExecution: readonly [Static<typeof Core.CommandExecutionFactsSchema>];
  readonly planGoalContinuation: readonly [Static<typeof Core.GoalContinuationFactsSchema>];
  readonly rollbackGoalCommand: readonly [Static<typeof Core.GoalRollbackFactsSchema>];
  readonly cronPoll: readonly [Static<typeof Core.CronPollFactsSchema>];
  readonly cronDelivered: readonly [Static<typeof Core.CronDeliveredFactsSchema>];
  readonly cronGoalFacts: readonly [Static<typeof Core.CronContextFactsSchema>];
  readonly createCronGoal: readonly [Static<typeof Action.CronGoalCreationFactsSchema>];
  readonly cronStartup: readonly [Static<typeof Core.CronStartupFactsSchema>];
  readonly cronUpdateTask: readonly [Static<typeof Core.CronTaskUpdateFactsSchema>];
  readonly handleCronManagerCommand: readonly [Static<typeof Core.CronManagerCommandFactsSchema>];
  readonly refreshFooterState: readonly [HostContext];
  readonly updateFooterThinking: readonly ["off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max", HostContext];
  readonly planChildGoalContinuation: readonly [HostGoalEntry];
  readonly startGoalTurn: readonly [];
  readonly goalClockPauseStart: readonly [];
  readonly goalClockPauseEnd: readonly [];
  readonly interruptGoalAutomation: readonly [HostContext];
  readonly clearInterruptedGoalAutomation: readonly [HostContext];
  readonly finalizeGoalError: readonly [Static<typeof Core.FinalizeGoalErrorFactsSchema>];
  readonly planCommandChildSession: readonly [Static<typeof Core.CommandChildSessionFactsSchema>];
  readonly planCommandChildDispatch: readonly [Static<typeof Core.CommandChildDispatchFactsSchema>];
  readonly finishCommandChildDispatch: readonly [Static<typeof Core.CommandChildDispatchFinishFactsSchema>];
  readonly persistRalphControllerState: readonly [HostContext];
  readonly recordAgentChildSessionStartAuthorized: readonly [Static<typeof Action.RecordAgentChildSessionStartFactsSchema>, Core.AgentActionCapabilityFacts, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly agentRoutingDiagnostics: readonly [];
  readonly rollbackUnacceptedAgentStart: readonly [Static<typeof Action.RollbackUnacceptedAgentStartFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly rollbackAgentSendPreflight: readonly [Static<typeof Action.RollbackAgentSendPreflightFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly recordAgentSendDispatchFailure: readonly [Static<typeof Action.RecordAgentSendDispatchFailureFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly rollbackFailedAgentInterruption: readonly [Static<typeof Action.RollbackFailedAgentInterruptionFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly recordAgentDispatchCompletion: readonly [Static<typeof Action.AgentDispatchCompletionFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly recordAgentActivity: readonly [Static<typeof Action.AgentActivityFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly recordAgentDispatchBoundaryAuthorized: readonly [Static<typeof Action.AgentDispatchBoundaryFactsSchema>, Core.AgentActionCapabilityFacts, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly reconcileLiveAgentDispatches: readonly [Static<typeof Action.LiveAgentDispatchesFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly pendingAgentNotifications: readonly [Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly recordAgentBackgroundNotification: readonly [Static<typeof Action.AgentRunIdFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly releaseAgentBackgroundNotification: readonly [Static<typeof Action.AgentRunIdFactsSchema>];
  readonly validateAgentBackgroundNotificationClaim: readonly [Static<typeof Action.AgentRunIdFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly countActiveChildRuns: readonly [Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly ephemeralAgentCleanupPlan: readonly [Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly agentManagerSnapshot: readonly [Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly finishEphemeralAgentCleanup: readonly [Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly releaseEphemeralAgentCleanupLease: readonly [Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly suspendOwnerAgentsOnShutdown: readonly [Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly finishAgentWait: readonly [Static<typeof Action.FinishAgentWaitFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly finishAgentClose: readonly [Static<typeof Action.AgentIdFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly claimAgentAction: readonly [Core.AgentActionCapabilityFacts];
  readonly revalidateAgentAction: readonly [Core.AgentActionCapabilityFacts];
  readonly ratchetAgentAction: readonly [Core.AgentActionCapabilityFacts];
  readonly authorizeAgentActionCleanup: readonly [Core.AgentActionCapabilityFacts];
  readonly prepareAgentCloseStop: readonly [Core.AgentActionCapabilityFacts];
  readonly completeAgentCloseStop: readonly [Core.AgentActionCapabilityFacts];
  readonly releaseAgentAction: readonly [Core.AgentActionCapabilityFacts];
  readonly acceptAgentWorktreeStart: readonly [Static<typeof Action.AgentIdFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly rollbackAgentWorktreeStart: readonly [Static<typeof Action.AgentIdFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly deleteAgentWorktree: readonly [Static<typeof Action.AgentIdFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly reconcileProvisionalAgentWorktrees: readonly [];
  readonly cancelAgentBrokerSessions: readonly [Static<typeof Action.AgentIdFactsSchema>];
  readonly deleteAgentChildSession: readonly [Static<typeof Action.AgentIdFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly recordAgentCloseCleanupFailure: readonly [Static<typeof Action.AgentIdFactsSchema>, Static<typeof Core.AgentOwnerContextFactsSchema>];
  readonly handleCommand: readonly [Static<typeof Action.HandleCommandFactsSchema>];
  readonly handleComposerCommand: readonly [Static<typeof Action.ComposerCommandFactsSchema>];
  readonly planCommandNotification: readonly [Static<typeof Core.CommandNotificationFactsSchema>];
  readonly visibilityRows: readonly [Static<typeof Core.VisibilityRowsFactsSchema>];
  readonly visibilitySaveProjectPlan: readonly [Static<typeof Core.VisibilityRowsFactsSchema>];
  readonly visibilityListCommand: readonly [Static<typeof Core.VisibilityRowsFactsSchema>];
  readonly toggleVisibilityRow: readonly [Static<typeof Core.VisibilityToggleFactsSchema>];
  readonly visibilityWarnings: readonly [Static<typeof Core.VisibilityWarningFactsSchema>];
  readonly reloadSessionState: readonly [HostContext];
  readonly planCronPrompt: readonly [Static<typeof Core.CronPromptFactsSchema>];
  readonly finishCronPrompt: readonly [Static<typeof Core.CronPromptPlanSchema>, Static<typeof Action.CronPromptSelectionSchema>, HostContext];
  readonly planPermissionsPrompt: readonly [Static<typeof Core.PermissionsPromptFactsSchema>];
  readonly finishPermissionsPrompt: readonly [Static<typeof Core.PermissionsPromptFinishFactsSchema>];
  readonly toolResultEnvelope: readonly [Action.ToolResultConstructionFacts];
  readonly hostToolResult: readonly [Action.HostToolResultFacts];
  readonly toolResultToCommandResult: readonly [Static<typeof Core.ToolResultEnvelopeSchema>];
  readonly runThreadTool: readonly [Static<typeof Core.ThreadToolFactsSchema>];
  readonly planThreadCatalogScans: readonly [Static<typeof Core.ThreadCatalogFactsSchema>];
  readonly openAiUsageHostAuth: readonly [];
  readonly openAiUsageHostParams: readonly [Static<typeof Core.OpenAiUsageHostLookupFactsSchema>];
  readonly executeOpenAiUsage: readonly [Static<typeof Core.OpenAiUsageHostParamsSchema>, HostContext];
  readonly executeExa: readonly [Static<typeof Core.ExaExecutionFactsSchema>];
  readonly approveExaPlan: readonly [Static<typeof Core.ExaExecutionFactsSchema>];
};

export type CoreMethodName = keyof CoreMethodArgs;
export type CoreBridge = {
  readonly call: <K extends CoreMethodName>(name: K, args: CoreMethodArgs[K]) => unknown;
};
